DROP TABLE IF EXISTS TAG;
DROP TABLE IF EXISTS PHONE;
DROP TABLE IF EXISTS CONTACT;

CREATE TABLE CONTACT (
    ID INTEGER NOT NULL PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL
);

CREATE TABLE PHONE (
    ID INTEGER NOT NULL PRIMARY KEY,
    CONTACT_ID INTEGER NOT NULL,
    TYPE VARCHAR(32) NOT NULL,
    PHONE VARCHAR(32) NOT NULL
);

CREATE TABLE TAG (
    ID INTEGER NOT NULL PRIMARY KEY,
    PHONE_ID INTEGER NOT NULL,
    NAME VARCHAR(64) NOT NULL
);

ALTER TABLE PHONE ADD CONSTRAINT FK_PHONE_CONTACT_ID FOREIGN KEY (CONTACT_ID) REFERENCES CONTACT (ID);
ALTER TABLE TAG ADD CONSTRAINT FK_TAG_PHONE_ID FOREIGN KEY (PHONE_ID) REFERENCES PHONE (ID);

INSERT INTO CONTACT (ID, NAME) VALUES (1, 'Govind');
INSERT INTO CONTACT (ID, NAME) VALUES (2, 'Krishna');
INSERT INTO CONTACT (ID, NAME) VALUES (3, 'Madhav');

INSERT INTO PHONE (ID, CONTACT_ID, TYPE, PHONE) VALUES (101, 1, 'mobile', '+91-080-5555-0101');
INSERT INTO PHONE (ID, CONTACT_ID, TYPE, PHONE) VALUES (102, 1, 'office', '+91-080-5555-0102');
INSERT INTO PHONE (ID, CONTACT_ID, TYPE, PHONE) VALUES (201, 2, 'mobile', '+91-080-5555-0201');
INSERT INTO PHONE (ID, CONTACT_ID, TYPE, PHONE) VALUES (301, 3, 'office', '+91-080-5555-0301');

INSERT INTO TAG (ID, PHONE_ID, NAME) VALUES (1001, 101, 'primary');
INSERT INTO TAG (ID, PHONE_ID, NAME) VALUES (1002, 101, 'sms');
INSERT INTO TAG (ID, PHONE_ID, NAME) VALUES (1003, 102, 'work');
INSERT INTO TAG (ID, PHONE_ID, NAME) VALUES (2001, 201, 'primary');
